### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by teddyvn** [ozguryazilimas/redmine_required_field#1]
Thanks you for very useful plugin.
Could you add the following features into this plugin?

1. Add a red star after "Spent time" label
2. Allow configure by Tracker. It means that some trackers such as Bug is required.
Thanks you very much.

**Comment by zaburt** [comment]
We will add these features. For the tracker requirement I am thinking to change the config system so that admins can define multiple configurations where each configuration entry can be made up of multiple selected issue statuses, multiple selected projects and trackers. You will be able to create multiple of these. Do you see any issues with this ?

**Comment by teddyvn** [comment]
Thank you very much, zaburt!
I am looking forward to receiving the new version.

**Comment by zaburt** [comment]
These changes are in. There is a new configuration system, see the README, please don't forget to click Apply to save configuration changes. Displaying of red star is dynamic since it can depend on tracker, issue status which can be changed on the issue edit page.

Also note that master branch is for Redmine 4.x now, if you want to use Redmine 3 you need to use `redmine3` branch.
